<?php
/**
 * MM_PixelManager
 *
 * @category    MM
 * @package     MM_PixelManager
 * @copyright   Copyright (c) 2016 MM. (http://blog.meumagento.com.br)
 */
class MM_PixelManager_Block_Adminhtml_Pixel_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    /**
     * MM_PixelManager_Block_Adminhtml_Pixel_Grid constructor.
     */
    public function __construct() {
        parent::__construct();
        $this->setId('pixelmanagerGrid');
        $this->setDefaultSort('entity_id');
        $this->setDefaultDir('asc');
        $this->setSaveParametersInSession(true);
        $this->setUseAjax(true);
    }

    /**
     * Prepare grid collection object
     *
     * @return Mage_Adminhtml_Block_Widget_Grid
     */
    protected function _prepareCollection()
    {
        $collection = Mage::getModel('mm_pixelmanager/pixel')->getCollection();
        $this->setCollection($collection);
        return $this;
    }

    /**
     * @return $this
     * @throws Exception
     */
    protected function _prepareColumns()
    {
        $this->addColumn('entity_id', array(
            'header'    => Mage::helper('mm_pixelmanager')->__('ID'),
            'index'     => 'entity_id',
            'type'      => 'int'
        ));

        $this->addColumn('name', array(
            'header'    => Mage::helper('mm_pixelmanager')->__('Name'),
            'index'     => 'name',
            'type'      => 'text'
        ));

        $this->addColumn('action', array(
            'header'    => Mage::helper('mm_pixelmanager')->__('Action'),
            'index'     => 'action',
            'type'      => 'options',
            'options'   => $this->_getHelper()->getActionListOptions()

        ));

        $this->addColumn('place', array(
            'header'    => Mage::helper('mm_pixelmanager')->__('Place'),
            'index'     => 'place',
            'type'      => 'options',
            'options'   => $this->_getHelper()->getPlaceListOptions()

        ));

        $this->addColumn('is_active', array(
            'header'    => Mage::helper('mm_pixelmanager')->__('Is Active'),
            'index'     => 'is_active',
            'type'      => 'options',
            'options'   => Mage::getSingleton('adminhtml/system_config_source_yesno')->toArray()
        ));

        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getGridUrl()
    {
        return $this->getUrl('*/*/grid', array('_current'=>true));
    }

    /**
     * @param $row
     * @return string
     * @throws Exception
     */
    public function getRowUrl($row)
    {
        return $this->getUrl('*/*/edit', array(
                'store'=>$this->getRequest()->getParam('store'),
                'id'=>$row->getId())
        );
    }

    /**
     * @return MM_PixelManager_Helper_Data
     */
    private function _getHelper()
    {
        return Mage::helper('mm_pixelmanager');
    }

}